### PR TITLE
Added es.lua (spanish)

### PR DESCRIPTION
**Pull request by buddizer**
Describe Pull request
Created es.lua with spanish translation.

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
Does your code fit the style guidelines? Yes
Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by buddizer** [comment]
Could we merge this?

**Review by tom-osborne — APPROVED** [review]

**Comment by tom-osborne** [comment]
> Could we merge this?

Can you remove the en.lua from this PR as it has since been updated. We will then get it merged.

**Comment by buddizer** [comment]
> > Could we merge this?
> 
> Can you remove the en.lua from this PR as it has since been updated. We will then get it merged.

Updated.

**Review by tom-osborne — APPROVED** [review]
PR approved. Thanks

**Pull request merged**
